### ISSUE TITLE
std::span overloads for PipelineBaseCreateInfo

### ISSUE THREAD

**Issue by Tearnote** [martty/vuk#59]
`PipelineBaseCreateInfo` functions like `add_spirv()` currently take the source as `std::vector`. This makes sense for sources loaded at runtime, but requires a needless copy if the sources are embedded in the executable. These functions could have variants that accept a `std::span`, with the requirement that the underlying buffer will live as long as the vuk context. This is low priority but would reduce API friction a little in this scenario.

This would probably need a change to `ShaderSource` so that it owns a span and optionally a vector of data.

**Comment by martty** [comment]
Added in f3f1c9c9f09817f5d0b1f45fa977a02bcaa9165e.
