### ISSUE TITLE
Missing CommandBuffer overloads

### ISSUE THREAD

**Issue by Tearnote** [martty/vuk#62]
Most `CommandBuffer` member functions, like `bind_buffer`, can take either a `Buffer` or a `Name`. Some of them though, like `bind_index_buffer` or `draw_indexed_indirect`, take only a `Buffer`, and that needs to be worked around with the verbose `*cmd.get_resource_buffer("bufferName")`. Would be nice to have full feature parity for names here.

**Comment by martty** [comment]
Fixed in 62589e0ee83c335c0c5db2e90052e63b6692628f - please reopen if there is still some missing.
