### ISSUE TITLE
Do not load debug utils function pointers

### ISSUE THREAD

**Issue by DethRaid** [martty/vuk#70]
Currently, Vuk loads the function pointers for the debug utils functions itself. This fails on my system. My Android phone does not provide the debug utils extension itself, so trying to load the function pointers from the system fails

Volk is able to load the function pointers for the debug utils functions just fine, however. The Vulkan validation layers provide the debug utils extension for systems such as mine, and Volk is able to load the debug utils functions from those layers. I'm not entirely sure how Volk does it

I've gotten unblocked locally by changing the places where Vuk uses debug utils functions to use the function pointers from Volk

**Comment by martty** [comment]
Thank you for reporting, from e59e0e2 onwards you will have to load pointers yourself and pass it in for vuk to use.
